<?php
// REGISTER CUSTOM BLOCK
add_action('acf/init', 'favorite_cards_register_block');
function favorite_cards_register_block()
{
  if (function_exists('acf_register_block')) {
    acf_register_block(array(
      'name'              => 'favorite-cards',
      'title'             => __('My Favorite Cards'),
      'description'       => __('Block to show a My Favorite Cards.'),
      'render_callback'   => 'favorite_cards_render',
      'category'          => 'formatting',
      'icon'              => 'money-alt',
      'keywords'          => array('cards', 'favorite', 'banner'),
    ));
  }
}

// RENDER FUNCTION FOR CUSTOM BLOCK
function favorite_cards_render($block)
{

  // convert name ("acf/block") into path friendly slug ("block")
  $slug = str_replace('acf/', '', $block['name']);

  // include a template part from folder
  if (file_exists(get_theme_file_path("/custom-blocks/{$slug}/{$slug}-template.php"))) {
    include(get_theme_file_path("/custom-blocks/{$slug}/{$slug}-template.php"));
  }
}


// FUNCTION TO FILL SELECT WITH CREDIT CARD INFO
function load_credit_cards_options_favorite_cards($field)
{
  // Reset choices
  $field['choices'] = array();
  
  // Get all Credit Card posts
  $cards = get_posts(array(
    'post_type' => 'credit_cards',
    'posts_per_page' => -1,
    'orderby' => 'title',
    'order' => 'ASC',
    'post_status' => 'publish'
  ));
  
  if($cards) {
    foreach($cards as $card) {
      $field['choices'][$card->ID] = $card->post_title;
    }
  }
  
  return $field;
}
add_filter('acf/load_field/name=fc_card_option', 'load_credit_cards_options_favorite_cards');

// CUSTOM BLOCK FIELDS
add_action('acf/include_fields', function () {
  if (! function_exists('acf_add_local_field_group')) {
    return;
  }

  acf_add_local_field_group(array(
    'key' => 'group_66cd51690090b',
    'title' => 'Favorite Cards [Custom Block]',
    'fields' => array(
      array(
        'key' => 'field_66cd5169c433c',
        'label' => 'My Favorite Cards',
        'name' => '',
        'aria-label' => '',
        'type' => 'accordion',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'open' => 0,
        'multi_expand' => 0,
        'endpoint' => 0,
      ),
      array(
        'key' => 'field_67c09af3d9a64',
        'label' => 'Content',
        'name' => '',
        'aria-label' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'top',
        'endpoint' => 0,
        'selected' => 0,
      ),
      array(
        'key' => 'field_66df5dc324a76',
        'label' => 'Is Widget?',
        'name' => 'is_widget',
        'aria-label' => '',
        'type' => 'true_false',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'ui_on_text' => 'Yes',
        'ui_off_text' => 'No',
        'ui' => 1,
      ),
      array(
        'key' => 'field_66cd51bcc433f',
        'label' => 'Title [line 1]',
        'name' => 'title_line_1',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_66cd51f0c4340',
        'label' => 'Title [line 2]',
        'name' => 'title_line_2',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_66cd51fbc4341',
        'label' => 'Left Image',
        'name' => 'left_image',
        'aria-label' => '',
        'type' => 'image',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'array',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
        'preview_size' => 'medium',
      ),
      array(
        'key' => 'field_66cd518bc433d',
        'label' => 'Favorite Cards',
        'name' => 'favorite_cards',
        'aria-label' => '',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'table',
        'pagination' => 0,
        'min' => 0,
        'max' => 0,
        'collapsed' => '',
        'button_label' => 'Add Row',
        'rows_per_page' => 20,
        'sub_fields' => array(
        array(
            'key' => 'field_66cd5198c433e',
            'label' => 'Card Option',
            'name' => 'fc_card_option',
            'type' => 'post_object',
            'post_type' => array('credit_cards'),
            'return_format' => 'id',
            'ui' => 1,
            'allow_null' => 0,
            'multiple' => 0,
            'parent_repeater' => 'field_66cd518bc433d',
        ),
        ),
      ),
      array(
        'key' => 'field_66cd55e90f105',
        'label' => 'CTA Label',
        'name' => 'cta_label',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_66cd55f70f106',
        'label' => 'CTA Url',
        'name' => 'cta_url',
        'aria-label' => '',
        'type' => 'url',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
      ),
      array(
        'key' => 'field_67c09adad9a63',
        'label' => 'Settings',
        'name' => '',
        'aria-label' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'top',
        'endpoint' => 0,
        'selected' => 0,
      ),
      array(
        'key' => 'field_67c09b34d9a65',
        'label' => 'Background Type',
        'name' => 'background_type',
        'aria-label' => '',
        'type' => 'select',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'choices' => array(
          'color' => 'Color',
          'gradient' => 'Gradient',
          'image' => 'Image',
        ),
        'default_value' => 'gradient',
        'return_format' => 'value',
        'multiple' => 0,
        'allow_null' => 0,
        'ui' => 0,
        'ajax' => 0,
        'placeholder' => '',
      ),
      array(
        'key' => 'field_67c09b61d9a66',
        'label' => 'Background Color',
        'name' => 'background_color',
        'aria-label' => '',
        'type' => 'color_picker',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_67c09b34d9a65',
              'operator' => '==',
              'value' => 'color',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'enable_opacity' => 0,
        'return_format' => 'string',
      ),
      array(
        'key' => 'field_67c09b71d9a67',
        'label' => 'Background Color Start',
        'name' => 'background_color_start',
        'aria-label' => '',
        'type' => 'color_picker',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_67c09b34d9a65',
              'operator' => '==',
              'value' => 'gradient',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '33.333',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '#9abfcc',
        'enable_opacity' => 0,
        'return_format' => 'string',
      ),
      array(
        'key' => 'field_67c09c17d9a68',
        'label' => 'Background Color End',
        'name' => 'background_color_end',
        'aria-label' => '',
        'type' => 'color_picker',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_67c09b34d9a65',
              'operator' => '==',
              'value' => 'gradient',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '33.333',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '#d3eff4',
        'enable_opacity' => 0,
        'return_format' => 'string',
      ),
      array(
        'key' => 'field_67c09c33d9a69',
        'label' => 'Rotation (Deg) (0-360)',
        'name' => 'rotation_deg',
        'aria-label' => '',
        'type' => 'number',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_67c09b34d9a65',
              'operator' => '==',
              'value' => 'gradient',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '33.333',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'min' => '',
        'max' => '',
        'placeholder' => '',
        'step' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_67c09c5fd9a6a',
        'label' => 'Background Image',
        'name' => 'background_image',
        'aria-label' => '',
        'type' => 'image',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_67c09b34d9a65',
              'operator' => '==',
              'value' => 'image',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'array',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
        'preview_size' => 'medium',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'block',
          'operator' => '==',
          'value' => 'acf/favorite-cards',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
  ));
});

add_action('acf/include_fields', function () {
  if (! function_exists('acf_add_local_field_group')) {
    return;
  }

  acf_add_local_field_group(array(
    'key' => 'group_66cd51690090b',
    'title' => 'Favorite Cards [Custom Block]',
    'fields' => array(
      array(
        'key' => 'field_66cd5169c433c',
        'label' => 'My Favorite Cards',
        'name' => '',
        'aria-label' => '',
        'type' => 'accordion',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'open' => 0,
        'multi_expand' => 0,
        'endpoint' => 0,
      ),
      array(
        'key' => 'field_67c09af3d9a64',
        'label' => 'Content',
        'name' => '',
        'aria-label' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'top',
        'endpoint' => 0,
        'selected' => 0,
      ),
      array(
        'key' => 'field_66df5dc324a76',
        'label' => 'Is Widget?',
        'name' => 'is_widget',
        'aria-label' => '',
        'type' => 'true_false',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'ui_on_text' => 'Yes',
        'ui_off_text' => 'No',
        'ui' => 1,
      ),
      array(
        'key' => 'field_66cd51bcc433f',
        'label' => 'Title [line 1]',
        'name' => 'title_line_1',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_66cd51f0c4340',
        'label' => 'Title [line 2]',
        'name' => 'title_line_2',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_66cd51fbc4341',
        'label' => 'Left Image',
        'name' => 'left_image',
        'aria-label' => '',
        'type' => 'image',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'array',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
        'preview_size' => 'medium',
      ),
      array(
        'key' => 'field_66cd518bc433d',
        'label' => 'Favorite Cards',
        'name' => 'favorite_cards',
        'aria-label' => '',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'table',
        'pagination' => 0,
        'min' => 0,
        'max' => 0,
        'collapsed' => '',
        'button_label' => 'Add Row',
        'rows_per_page' => 20,
        'sub_fields' => array(
          array(
            'key' => 'field_66cd5198c433e',
            'label' => 'Card Option',
            'name' => 'fc_card_option',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'choices' => array(
              0 => '﻿American Express® Gold Card',
              1 => 'Southwest® Rapid Rewards® Performance Business Credit Card',
              2 => 't.online/go.milevalue.com/southwest-performance-business-ofp?aff=ofp',
              3 => 'Southwest Rapid Rewards® Plus Credit Card',
              4 => 'Southwest Rapid Rewards® Premier Credit Card',
              5 => 'Southwest Rapid Rewards® Priority Credit Card',
              6 => 'Southwest® Rapid Rewards® Performance Business Credit Card',
              7 => 'Southwest® Rapid Rewards® Premier Business Credit Card',
              8 => 'Marriott Bonvoy Boundless® Credit Card',
              9 => 'Marriott Bonvoy Brilliant® American Express® Card',
              10 => 'Marriott Bonvoy Business® American Express® Card',
              11 => 'Chase Sapphire Preferred® Card',
              12 => 'Chase Sapphire Reserve®',
              13 => 'Ink Business Cash® Credit Card',
              14 => 'Ink Business Preferred® Credit Card',
              15 => 'Ink Business Unlimited® Credit Card',
              16 => 'Capital One Venture Rewards Credit Card',
              17 => 'Capital One Venture X Business',
              18 => 'Capital One Venture X Rewards Credit Card',
              19 => 'Delta SkyMiles® Blue American Express Card',
              20 => 'Delta SkyMiles® Gold American Express Card',
              21 => 'Delta SkyMiles® Gold Business American Express Card',
              22 => 'Delta SkyMiles® Platinum American Express Card',
              23 => 'Delta SkyMiles® Platinum Business American Express Card',
              24 => 'Delta SkyMiles® Reserve American Express Card',
              25 => 'Delta SkyMiles® Reserve Business American Express Card',
              26 => 'American Express® Business Gold Card',
              27 => 'American Express® Gold Card',
              28 => 'The Platinum Card® from American Express',
              29 => 'The Business Platinum Card® from American Express',
              30 => 'Hilton Honors American Express Card',
              31 => 'Hilton Honors American Express Surpass® Card',
              32 => 'The Hilton Honors American Express Business Card',
            ),
            'default_value' => false,
            'return_format' => 'value',
            'multiple' => 0,
            'allow_null' => 0,
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
            'parent_repeater' => 'field_66cd518bc433d',
          ),
        ),
      ),
      array(
        'key' => 'field_66cd55e90f105',
        'label' => 'CTA Label',
        'name' => 'cta_label',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_66cd55f70f106',
        'label' => 'CTA Url',
        'name' => 'cta_url',
        'aria-label' => '',
        'type' => 'url',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
      ),
      array(
        'key' => 'field_67c09adad9a63',
        'label' => 'Settings',
        'name' => '',
        'aria-label' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'top',
        'endpoint' => 0,
        'selected' => 0,
      ),
      array(
        'key' => 'field_67c09b34d9a65',
        'label' => 'Background Type',
        'name' => 'background_type',
        'aria-label' => '',
        'type' => 'select',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'choices' => array(
          'color' => 'Color',
          'gradient' => 'Gradient',
          'image' => 'Image',
        ),
        'default_value' => 'gradient',
        'return_format' => 'value',
        'multiple' => 0,
        'allow_null' => 0,
        'ui' => 0,
        'ajax' => 0,
        'placeholder' => '',
      ),
      array(
        'key' => 'field_67c09b61d9a66',
        'label' => 'Background Color',
        'name' => 'background_color',
        'aria-label' => '',
        'type' => 'color_picker',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_67c09b34d9a65',
              'operator' => '==',
              'value' => 'color',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'enable_opacity' => 0,
        'return_format' => 'string',
      ),
      array(
        'key' => 'field_67c09b71d9a67',
        'label' => 'Background Color Start',
        'name' => 'background_color_start',
        'aria-label' => '',
        'type' => 'color_picker',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_67c09b34d9a65',
              'operator' => '==',
              'value' => 'gradient',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '33.333',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '#9abfcc',
        'enable_opacity' => 0,
        'return_format' => 'string',
      ),
      array(
        'key' => 'field_67c09c17d9a68',
        'label' => 'Background Color End',
        'name' => 'background_color_end',
        'aria-label' => '',
        'type' => 'color_picker',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_67c09b34d9a65',
              'operator' => '==',
              'value' => 'gradient',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '33.333',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '#d3eff4',
        'enable_opacity' => 0,
        'return_format' => 'string',
      ),
      array(
        'key' => 'field_67c09c33d9a69',
        'label' => 'Rotation (Deg) (0-360)',
        'name' => 'rotation_deg',
        'aria-label' => '',
        'type' => 'number',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_67c09b34d9a65',
              'operator' => '==',
              'value' => 'gradient',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '33.333',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'min' => '',
        'max' => '',
        'placeholder' => '',
        'step' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_67c09c5fd9a6a',
        'label' => 'Background Image',
        'name' => 'background_image',
        'aria-label' => '',
        'type' => 'image',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_67c09b34d9a65',
              'operator' => '==',
              'value' => 'image',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'array',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
        'preview_size' => 'medium',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'block',
          'operator' => '==',
          'value' => 'acf/favorite-cards',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
  ));
});

add_action('acf/include_fields', function () {
  if (! function_exists('acf_add_local_field_group')) {
    return;
  }

  acf_add_local_field_group(array(
    'key' => 'group_66cd51690090b',
    'title' => 'Favorite Cards [Custom Block]',
    'fields' => array(
      array(
        'key' => 'field_66cd5169c433c',
        'label' => 'My Favorite Cards',
        'name' => '',
        'aria-label' => '',
        'type' => 'accordion',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'open' => 0,
        'multi_expand' => 0,
        'endpoint' => 0,
      ),
      array(
        'key' => 'field_67c09af3d9a64',
        'label' => 'Content',
        'name' => '',
        'aria-label' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'top',
        'endpoint' => 0,
        'selected' => 0,
      ),
      array(
        'key' => 'field_66df5dc324a76',
        'label' => 'Is Widget?',
        'name' => 'is_widget',
        'aria-label' => '',
        'type' => 'true_false',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'ui_on_text' => 'Yes',
        'ui_off_text' => 'No',
        'ui' => 1,
      ),
      array(
        'key' => 'field_66cd51bcc433f',
        'label' => 'Title [line 1]',
        'name' => 'title_line_1',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_66cd51f0c4340',
        'label' => 'Title [line 2]',
        'name' => 'title_line_2',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_66cd51fbc4341',
        'label' => 'Left Image',
        'name' => 'left_image',
        'aria-label' => '',
        'type' => 'image',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'array',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
        'preview_size' => 'medium',
      ),
      array(
        'key' => 'field_66cd518bc433d',
        'label' => 'Favorite Cards',
        'name' => 'favorite_cards',
        'aria-label' => '',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'table',
        'pagination' => 0,
        'min' => 0,
        'max' => 0,
        'collapsed' => '',
        'button_label' => 'Add Row',
        'rows_per_page' => 20,
        'sub_fields' => array(
          array(
            'key' => 'field_66cd5198c433e',
            'label' => 'Card Option',
            'name' => 'fc_card_option',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'choices' => array(
              0 => '﻿American Express® Gold Card',
              1 => 'Southwest® Rapid Rewards® Performance Business Credit Card',
              2 => 't.online/go.milevalue.com/southwest-performance-business-ofp?aff=ofp',
              3 => 'Southwest Rapid Rewards® Plus Credit Card',
              4 => 'Southwest Rapid Rewards® Premier Credit Card',
              5 => 'Southwest Rapid Rewards® Priority Credit Card',
              6 => 'Southwest® Rapid Rewards® Performance Business Credit Card',
              7 => 'Southwest® Rapid Rewards® Premier Business Credit Card',
              8 => 'Marriott Bonvoy Boundless® Credit Card',
              9 => 'Marriott Bonvoy Brilliant® American Express® Card',
              10 => 'Marriott Bonvoy Business® American Express® Card',
              11 => 'Chase Sapphire Preferred® Card',
              12 => 'Chase Sapphire Reserve®',
              13 => 'Ink Business Cash® Credit Card',
              14 => 'Ink Business Preferred® Credit Card',
              15 => 'Ink Business Unlimited® Credit Card',
              16 => 'Capital One Venture Rewards Credit Card',
              17 => 'Capital One Venture X Business',
              18 => 'Capital One Venture X Rewards Credit Card',
              19 => 'Delta SkyMiles® Blue American Express Card',
              20 => 'Delta SkyMiles® Gold American Express Card',
              21 => 'Delta SkyMiles® Gold Business American Express Card',
              22 => 'Delta SkyMiles® Platinum American Express Card',
              23 => 'Delta SkyMiles® Platinum Business American Express Card',
              24 => 'Delta SkyMiles® Reserve American Express Card',
              25 => 'Delta SkyMiles® Reserve Business American Express Card',
              26 => 'American Express® Business Gold Card',
              27 => 'American Express® Gold Card',
              28 => 'The Platinum Card® from American Express',
              29 => 'The Business Platinum Card® from American Express',
              30 => 'Hilton Honors American Express Card',
              31 => 'Hilton Honors American Express Surpass® Card',
              32 => 'The Hilton Honors American Express Business Card',
            ),
            'default_value' => false,
            'return_format' => 'value',
            'multiple' => 0,
            'allow_null' => 0,
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
            'parent_repeater' => 'field_66cd518bc433d',
          ),
        ),
      ),
      array(
        'key' => 'field_66cd55e90f105',
        'label' => 'CTA Label',
        'name' => 'cta_label',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_66cd55f70f106',
        'label' => 'CTA Url',
        'name' => 'cta_url',
        'aria-label' => '',
        'type' => 'url',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
      ),
      array(
        'key' => 'field_67c09adad9a63',
        'label' => 'Settings',
        'name' => '',
        'aria-label' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'top',
        'endpoint' => 0,
        'selected' => 0,
      ),
      array(
        'key' => 'field_67c09b34d9a65',
        'label' => 'Background Type',
        'name' => 'background_type',
        'aria-label' => '',
        'type' => 'select',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'choices' => array(
          'color' => 'Color',
          'gradient' => 'Gradient',
          'image' => 'Image',
        ),
        'default_value' => 'gradient',
        'return_format' => 'value',
        'multiple' => 0,
        'allow_null' => 0,
        'ui' => 0,
        'ajax' => 0,
        'placeholder' => '',
      ),
      array(
        'key' => 'field_67c09b61d9a66',
        'label' => 'Background Color',
        'name' => 'background_color',
        'aria-label' => '',
        'type' => 'color_picker',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_67c09b34d9a65',
              'operator' => '==',
              'value' => 'color',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'enable_opacity' => 0,
        'return_format' => 'string',
      ),
      array(
        'key' => 'field_67c09b71d9a67',
        'label' => 'Background Color Start',
        'name' => 'background_color_start',
        'aria-label' => '',
        'type' => 'color_picker',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_67c09b34d9a65',
              'operator' => '==',
              'value' => 'gradient',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '33.333',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '#9abfcc',
        'enable_opacity' => 0,
        'return_format' => 'string',
      ),
      array(
        'key' => 'field_67c09c17d9a68',
        'label' => 'Background Color End',
        'name' => 'background_color_end',
        'aria-label' => '',
        'type' => 'color_picker',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_67c09b34d9a65',
              'operator' => '==',
              'value' => 'gradient',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '33.333',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '#d3eff4',
        'enable_opacity' => 0,
        'return_format' => 'string',
      ),
      array(
        'key' => 'field_67c09c33d9a69',
        'label' => 'Rotation (Deg) (0-360)',
        'name' => 'rotation_deg',
        'aria-label' => '',
        'type' => 'number',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_67c09b34d9a65',
              'operator' => '==',
              'value' => 'gradient',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '33.333',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'min' => '',
        'max' => '',
        'placeholder' => '',
        'step' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_67c09c5fd9a6a',
        'label' => 'Background Image',
        'name' => 'background_image',
        'aria-label' => '',
        'type' => 'image',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_67c09b34d9a65',
              'operator' => '==',
              'value' => 'image',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'array',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
        'preview_size' => 'medium',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'block',
          'operator' => '==',
          'value' => 'acf/favorite-cards',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
  ));
});
