<?php
// REGISTER CUSTOM BLOCK
add_action('acf/init', 'favorite_things_register_block');
function favorite_things_register_block()
{
  if (function_exists('acf_register_block')) {
    acf_register_block(array(
      'name'              => 'favorite-things',
      'title'             => __('Favorite Things'),
      'description'       => __('Block to show a Favorite Things.'),
      'render_callback'   => 'favorite_things_render',
      'category'          => 'formatting',
      'icon'              => 'heart',
      'keywords'          => array('cards', 'favorite', 'banner'),
    ));
  }
}

// RENDER FUNCTION FOR CUSTOM BLOCK
function favorite_things_render($block)
{

  // convert name ("acf/block") into path friendly slug ("block")
  $slug = str_replace('acf/', '', $block['name']);

  // include a template part from folder
  if (file_exists(get_theme_file_path("/custom-blocks/{$slug}/{$slug}-template.php"))) {
    include(get_theme_file_path("/custom-blocks/{$slug}/{$slug}-template.php"));
  }
}

// CUSTOM BLOCK FIELDS
add_action('acf/include_fields', function () {
  if (! function_exists('acf_add_local_field_group')) {
    return;
  }

  acf_add_local_field_group(array(
    'key' => 'group_66fc29346cfc7',
    'title' => 'Favorite Things [Custom Block]',
    'fields' => array(
      array(
        'key' => 'field_66fc2934724bb',
        'label' => 'Favorite Things',
        'name' => '',
        'aria-label' => '',
        'type' => 'accordion',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'open' => 0,
        'multi_expand' => 0,
        'endpoint' => 0,
      ),
      array(
        'key' => 'field_66fc2934724d0',
        'label' => 'Content',
        'name' => '',
        'aria-label' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'top',
        'endpoint' => 0,
        'selected' => 0,
      ),
      array(
        'key' => 'field_66fdb55190cff',
        'label' => 'Rotating Image',
        'name' => 'rotating_image',
        'aria-label' => '',
        'type' => 'group',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'sub_fields' => array(
          array(
            'key' => 'field_66fdb59390d00',
            'label' => 'Image',
            'name' => 'image',
            'aria-label' => '',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
            'return_format' => 'array',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
            'preview_size' => 'medium',
          ),
          array(
            'key' => 'field_66fdb5a790d01',
            'label' => 'Rotating Image',
            'name' => 'rotating_image',
            'aria-label' => '',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
            'return_format' => 'array',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
            'preview_size' => 'medium',
          ),
          array(
            'key' => 'field_66fdb5cc90d02',
            'label' => 'Top',
            'name' => 'top',
            'aria-label' => '',
            'type' => 'number',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '25',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'min' => '',
            'max' => '',
            'placeholder' => '',
            'step' => '',
            'prepend' => '',
            'append' => '',
          ),
          array(
            'key' => 'field_66fdb5e390d05',
            'label' => 'Bottom',
            'name' => 'bottom',
            'aria-label' => '',
            'type' => 'number',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '25',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'min' => '',
            'max' => '',
            'placeholder' => '',
            'step' => '',
            'prepend' => '',
            'append' => '',
          ),
          array(
            'key' => 'field_66fdb5e290d04',
            'label' => 'Left',
            'name' => 'left',
            'aria-label' => '',
            'type' => 'number',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '25',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'min' => '',
            'max' => '',
            'placeholder' => '',
            'step' => '',
            'prepend' => '',
            'append' => '',
          ),
          array(
            'key' => 'field_66fdb5e190d03',
            'label' => 'Right',
            'name' => 'right',
            'aria-label' => '',
            'type' => 'number',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '25',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'min' => '',
            'max' => '',
            'placeholder' => '',
            'step' => '',
            'prepend' => '',
            'append' => '',
          ),
        ),
      ),
      array(
        'key' => 'field_66fdb6f090d06',
        'label' => 'Title',
        'name' => 'title',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_66fdba0e4f527',
        'label' => 'SubTitle',
        'name' => 'subtitle',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_66fdba444f528',
        'label' => 'Favorite Things',
        'name' => 'favorite_things',
        'aria-label' => '',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'pagination' => 1,
        'rows_per_page' => 3,
        'min' => 0,
        'max' => 0,
        'collapsed' => '',
        'button_label' => 'Add Row',
        'sub_fields' => array(
          array(
            'key' => 'field_66fdbab94f529',
            'label' => 'Image',
            'name' => 'image',
            'aria-label' => '',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'return_format' => 'array',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
            'preview_size' => 'medium',
            'parent_repeater' => 'field_66fdba444f528',
          ),
          array(
            'key' => 'field_66fdbcedf4f8b',
            'label' => 'Title',
            'name' => 'title',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'parent_repeater' => 'field_66fdba444f528',
          ),
          array(
            'key' => 'field_66fdbac84f52a',
            'label' => 'Description',
            'name' => 'description',
            'aria-label' => '',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 1,
            'delay' => 0,
            'parent_repeater' => 'field_66fdba444f528',
          ),
          array(
            'key' => 'field_66fdbad54f52b',
            'label' => 'CTA Label',
            'name' => 'cta_label',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'parent_repeater' => 'field_66fdba444f528',
          ),
          array(
            'key' => 'field_66fdbaea4f52c',
            'label' => 'CTA Url',
            'name' => 'cta_url',
            'aria-label' => '',
            'type' => 'url',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'parent_repeater' => 'field_66fdba444f528',
          ),
          array(
            'key' => 'field_66fdbaf64f52d',
            'label' => 'Title Color',
            'name' => 'title_color',
            'aria-label' => '',
            'type' => 'color_picker',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '#222',
            'enable_opacity' => 0,
            'return_format' => 'string',
            'parent_repeater' => 'field_66fdba444f528',
          ),
          array(
            'key' => 'field_66fdbb064f52e',
            'label' => 'Description Color',
            'name' => 'description_color',
            'aria-label' => '',
            'type' => 'color_picker',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '#222',
            'enable_opacity' => 0,
            'return_format' => 'string',
            'parent_repeater' => 'field_66fdba444f528',
          ),
          array(
            'key' => 'field_66fdbb1d4f52f',
            'label' => 'CTA Color',
            'name' => 'cta_color',
            'aria-label' => '',
            'type' => 'color_picker',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '#222',
            'enable_opacity' => 0,
            'return_format' => 'string',
            'parent_repeater' => 'field_66fdba444f528',
          ),
          array(
            'key' => 'field_66fdbb384f530',
            'label' => 'CTA Hover Color',
            'name' => 'cta_hover_color',
            'aria-label' => '',
            'type' => 'color_picker',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '#222',
            'enable_opacity' => 0,
            'return_format' => 'string',
            'parent_repeater' => 'field_66fdba444f528',
          ),
          array(
            'key' => 'field_67c08d42dcec9',
            'label' => 'Link In Description Color',
            'name' => 'link_in_description_color',
            'aria-label' => '',
            'type' => 'color_picker',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '#9bbfcd',
            'enable_opacity' => 0,
            'return_format' => 'string',
            'parent_repeater' => 'field_66fdba444f528',
          ),
          array(
            'key' => 'field_67c08d78dceca',
            'label' => 'Link In Description Hover Color',
            'name' => 'link_in_description_hover_color',
            'aria-label' => '',
            'type' => 'color_picker',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '#f0a9ad',
            'enable_opacity' => 0,
            'return_format' => 'string',
            'parent_repeater' => 'field_66fdba444f528',
          ),
        ),
      ),
      array(
        'key' => 'field_66fc2934724dd',
        'label' => 'Settings',
        'name' => '',
        'aria-label' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'top',
        'endpoint' => 0,
        'selected' => 0,
      ),
      array(
        'key' => 'field_66fc2934724f9',
        'label' => 'Background Type',
        'name' => 'background_type',
        'aria-label' => '',
        'type' => 'select',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'choices' => array(
          'color' => 'Color',
          'gradient' => 'Gradient',
          'image' => 'Image',
        ),
        'default_value' => 'color',
        'return_format' => 'value',
        'multiple' => 0,
        'allow_null' => 0,
        'ui' => 0,
        'ajax' => 0,
        'placeholder' => '',
      ),
      array(
        'key' => 'field_66fc293472501',
        'label' => 'Background Color',
        'name' => 'background_color',
        'aria-label' => '',
        'type' => 'color_picker',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_66fc2934724f9',
              'operator' => '==',
              'value' => 'color',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'enable_opacity' => 0,
        'return_format' => 'string',
      ),
      array(
        'key' => 'field_66fc293472508',
        'label' => 'Background Color Start',
        'name' => 'background_color_start',
        'aria-label' => '',
        'type' => 'color_picker',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_66fc2934724f9',
              'operator' => '==',
              'value' => 'gradient',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '33.333',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'enable_opacity' => 0,
        'return_format' => 'string',
      ),
      array(
        'key' => 'field_66fc29347250e',
        'label' => 'Background Color End',
        'name' => 'background_color_end',
        'aria-label' => '',
        'type' => 'color_picker',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_66fc2934724f9',
              'operator' => '==',
              'value' => 'gradient',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '33.333',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'enable_opacity' => 0,
        'return_format' => 'string',
      ),
      array(
        'key' => 'field_66fc293472514',
        'label' => 'Rotation (Deg) (0-360)',
        'name' => 'rotation_deg',
        'aria-label' => '',
        'type' => 'number',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_66fc2934724f9',
              'operator' => '==',
              'value' => 'gradient',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '33.333',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'min' => '',
        'max' => '',
        'placeholder' => '',
        'step' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_66fc29347251b',
        'label' => 'Background Image',
        'name' => 'background_image',
        'aria-label' => '',
        'type' => 'image',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_66fc2934724f9',
              'operator' => '==',
              'value' => 'image',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '33.333',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'array',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
        'preview_size' => 'medium',
      ),
      array(
        'key' => 'field_66fc293472521',
        'label' => 'Title Color',
        'name' => 'title_color',
        'aria-label' => '',
        'type' => 'color_picker',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '#222',
        'enable_opacity' => 0,
        'return_format' => 'string',
      ),
      array(
        'key' => 'field_66fc29347253a',
        'label' => 'Sub Title Color',
        'name' => 'sub_title_color',
        'aria-label' => '',
        'type' => 'color_picker',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '#F0A9AD',
        'enable_opacity' => 0,
        'return_format' => 'string',
      ),
      array(
        'key' => 'field_670c9f2ed76b2',
        'label' => 'Load More Text Color',
        'name' => 'load_more_text_color',
        'aria-label' => '',
        'type' => 'color_picker',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '33.333',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '#FFF',
        'enable_opacity' => 0,
        'return_format' => 'string',
      ),
      array(
        'key' => 'field_670c9f5cd76b3',
        'label' => 'Load More Background Color',
        'name' => 'load_more_background_color',
        'aria-label' => '',
        'type' => 'color_picker',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '33.333',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '#F0A9AD',
        'enable_opacity' => 0,
        'return_format' => 'string',
      ),
      array(
        'key' => 'field_670c9f79d76b4',
        'label' => 'Load More Hover Color',
        'name' => 'load_more_hover_color',
        'aria-label' => '',
        'type' => 'color_picker',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '33.333',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '#9BBFCD',
        'enable_opacity' => 0,
        'return_format' => 'string',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'block',
          'operator' => '==',
          'value' => 'acf/favorite-things',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
  ));
});
